sonar.projectKey=fullstack-php-app
sonar.projectName=Fullstack PHP App
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/assets/**,**/vendor/**
